name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Auth to Google Cloud with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/508284363122/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2'
          service_account: 'sa-ci-cd-github@primal-gate-456620-t1.iam.gserviceaccount.com'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Get API name from XML
        id: get_api_name
        run: |
          # Extraction du nom de l'API depuis le fichier XML
          API_NAME=$(grep -oP '(?<=<name>)(.*)(?=</name>)' ./apiproxy/hello-world.xml)
          echo "API_NAME=$API_NAME" >> $GITHUB_ENV

      - name: Check extracted API name
        run: |
          echo "API Name Extracted: $API_NAME"

      - name: Check if API exists
        id: check_api
        run: |
          if [ -z "$API_NAME" ]; then
            echo "Error: API name is empty"
            exit 1
          fi
          API_EXISTS=$(gcloud apigee apis describe $API_NAME --project=primal-gate-456620-t1 --format="value(name)" || echo "not-found")
          echo "API_EXISTS=$API_EXISTS" >> $GITHUB_ENV

      - name: Create Apigee API Proxy if not exists
        if: env.API_EXISTS == 'not-found'
        run: |
          gcloud apigee apis import \
            --api=$API_NAME \
            --source=./curl-apigee-ci-cd/apiproxy \
            --project=primal-gate-456620-t1

      - name: Deploy Apigee Proxy
        if: env.API_EXISTS != 'not-found'
        run: |
          gcloud apigee apis deploy \
            --api=$API_NAME \
            --source=./curl-apigee-ci-cd/apiproxy \
            --project=primal-gate-456620-t1

      - name: Deploy to eval environment
        run: |
          gcloud apigee deployments create \
            --api=$API_NAME \
            --environment=eval \
            --revision=1 \
            --project=primal-gate-456620-t1
