name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Auth to Google Cloud with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/508284363122/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2'
          service_account: 'sa-ci-cd-github@primal-gate-456620-t1.iam.gserviceaccount.com'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Extract API name from XML
        id: get_api_name
        run: |
          API_NAME=$(sed -n 's/.*<APIProxy[^>]*name="\([^"]*\)".*/\1/p' ./apiproxy/hello-world.xml)
          echo "API_NAME=$API_NAME"
          echo "api_name=$API_NAME" >> $GITHUB_OUTPUT

      - name: Check if API exists
        id: check_api
        run: |
          API_NAME="${{ steps.get_api_name.outputs.api_name }}"
          API_EXISTS=$(gcloud apigee apis describe "$API_NAME" --project=primal-gate-456620-t1 --format="value(name)" || echo "not-found")
          echo "API_EXISTS=$API_EXISTS"
          echo "exists=$API_EXISTS" >> $GITHUB_OUTPUT

      - name: Import Apigee API Proxy if not exists
        if: steps.check_api.outputs.exists == 'not-found'
        run: |
          API_NAME="${{ steps.get_api_name.outputs.api_name }}"
          gcloud apigee apis import \
            --api="$API_NAME" \
            --source=./apiproxy \
            --project=primal-gate-456620-t1

      - name: Deploy to eval environment
        run: |
          API_NAME="${{ steps.get_api_name.outputs.api_name }}"
          echo "Deploying $API_NAME to eval environment..."

          gcloud apigee apis deploy \
            --api="$API_NAME" \
            --environment=eval \
            --source=./apiproxy \
            --project=primal-gate-456620-t1




